require:
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - "vendor/**/*"
    - "tmp/**/*"
    - "log/**/*"

Layout/LineLength:
  Max: 110

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Metrics/MethodLength:
  Max: 40

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Style/SymbolArray:
  EnforcedStyle: percent
