name: CI
on:
  push:
  pull_request:
jobs:
  ruby:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.5
          bundler-cache: true
      # Temporarily disable lint & tests until API keys set up
      # - run: bundle exec rubocop
      # - run: bundle exec rspec

