name: CI
on:
  push:
  pull_request:
jobs:
  ruby:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version-file: '.ruby-version'
          bundler-cache: true
      - run: bundle exec rubocop
      - run: bundle exec rspec
